## Tasca S3 T02

In [1]:
import numpy as np

### Exercici 1

In [2]:
arr1 = np.array([3,5,7])

In [3]:
#suma
sum(arr1)

15

In [4]:
#resta
print(arr1[1] * arr1[2])

35


In [5]:
#media
average = sum(arr1)/len(arr1)
print(average)

5.0


In [6]:
#mean
np.mean(arr1)

5.0

In [7]:
#median
np.median(arr1)

5.0

### Exercici 2

In [8]:
np.random.randint(101, size=(4,4))

array([[ 8, 81,  5, 86],
       [27, 80, 54, 92],
       [ 7, 29, 76, 54],
       [59, 46, 45, 80]])

### Exercici 3

In [9]:
arr2 = np.arange(1,13).reshape(4,3)
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
#total fila
f = np.sum(arr2, axis=1)
print(f)

[ 6 15 24 33]


In [11]:
#total columna
c = np.sum(arr2, axis=0)
print(c)

[22 26 30]


### Exercici 4

In [12]:
#introducir datos
altura = np.array([1.75, 1.59, 1.66, 1.66, 1.68])
peso = np.array([82, 68, 70, 61, 70])

In [13]:
#número total de elementos
n = len(altura)
print(n)

5


In [14]:
#Calcular la media de X
x_mean = np.mean(altura)
print(x_mean)

1.668


In [15]:
#calcular la media de Y
y_mean = np.mean(peso)
print(y_mean)

70.2


In [16]:
#calcular la desviación estandard de X
st_dev_x = np.std(altura)
print(st_dev_x)

0.051146847410177665


In [17]:
#calcular la desviación estandard de Y
st_dev_y = np.std(peso)
print(st_dev_y)

6.764613810115105


In [18]:
def num1(altura):
    list = []

    for n in altura:
        var1 = n - x_mean
        list.append(var1)
    
    return list

In [19]:
def num2(peso):
    list1 = []
    
    for p in peso:
        var2 = p - y_mean
        list1.append(var2)
    
    return list1

In [20]:
#calcular la distancia de cada punto X respecto a su media
num1(altura)

[0.08200000000000007,
 -0.07799999999999985,
 -0.008000000000000007,
 -0.008000000000000007,
 0.01200000000000001]

In [21]:
#calcular la distancia de cada punto Y respecto a su media
num2(peso)

[11.799999999999997,
 -2.200000000000003,
 -0.20000000000000284,
 -9.200000000000003,
 -0.20000000000000284]

In [22]:
#completamos el numerador de la ecuación
var3 = sum(np.multiply(num1(altura),num2(peso)))
print(var3)

1.2120000000000009


In [23]:
#hallamos el coeficiente de correlación
r = (1/n)*(var3)/(st_dev_x*st_dev_y)
print(round(r, 8))

0.70060098


In [24]:
#comparamos el resultado obtenido con el de la formula
np.corrcoef(altura, peso)

array([[1.        , 0.70060098],
       [0.70060098, 1.        ]])

Existeix una correlació positiva, on alçada i pes estan fortament relacionats